= Bolognese sauce

== ingredients:
* Olive oil
* One celery
* One carrot
* Two celery
* One onion
* 3 garlic cloves
* 500g ground beef
* 250g ground pork
* 500g of peeled tomatoes(or 800ml tomato puree)
* red vine
* salt
* bay leaf
* 100ml sweet cream

== Recipe

1. Chop the carrot, celery, onion and into fine pieces but not too fine
2. In a medium pot, add olive oil and the chopped vegetables and cook on low heat until the onion is transparent
3. Raise the heat to medium and add the ground beef and pork, stir and break it up as it cooks and browns
4. Raise the heat to high and add the red wine and cook until the wine has evaporated. The liquid should evaporate without burning the meat or veggies.
5. Lower the heat to medium and add the tomato paste and Tomato Puree
6. Add 2 bayleafes, salt and peper
7. Bring the sauce to a boil, then gradually lower the heat to the lowest level.
8. Let the sauce cook slow for about 3 hours, stir ocasionally
9. After 3 hours remove bayleafes and add milk and heat the sauce for about 7 minutes
