= Spaghetti carbonara

== Ingredients

- Guanciale
- Parmigiano Reggiano
- Egg yolks and whole eggs
- Spaghetti
- Pepper
- Garlic, optional

== Process

. Cut the guanciale into thick strips.
. Finely grate the parmigiana reggiano or pecorino.
. Sauce – Whisk together the egg, cheese and pepper in a large bowl. It needs to be a large bowl because the pasta will be stirred into the sauce in the bowl, off the stove, to avoid scrambling the eggs.
. Cook pasta – Bring 4 litres of water to the boil with 1 tablespoon of salt. Cook the pasta per packet directions. It should be firm, not soft, but fully cooked through.
. Reserve pasta cooking water – Just before draining, scoop out one cup of pasta cooking water. Then drain the pasta in a colander.
. Cook guanciale until golden while the pasta is cooking. You don’t need any oil, the guanciale will fry in its own fat.
. Toss pasta in guanciale – Tumble the hot pasta into the pan with the guanciale then toss so the pasta gets coated in the guanciale fat.
. Transfer into sauce bowl
. Add 1/2 cup pasta cooking water into the bowl.
. Mix vigorously with the handle of a wooden spoon, spinning the pasta around, for around 30 seconds to 1 minute. Watch as the watery pale yellow liquid transforms into a creamy sauce.
. Serve immediately in warm bowls.
