= INGREDIENTS

8 cups cold water

1/3 cup sour cream

3 1/2 Tbsp Vinegar divided

2 1/2 tsp Salt

3 Tbsp chopped dill (fresh or frozen)

1/2 cup green onion, finely chopped

1/2 ham diced

3-4 medium cooked potatoes, peeled and diced

3 hard-boiled eggs, diced

3-4 cucumbers, diced

== How to Make Okroshka


. Peel potatoes and dice them into 1/4″ cubes (we used the Vidalia Chopper). Place diced potatoes in a medium pot and cover with water. Add 1 Tbsp vinegar and bring to a boil then continue boiling for 10 minutes or until the potatoes are cooked, but not falling apart.

. Drain well and set aside to cool. For quicker cooling, you can rinse potatoes with cold water. (This cooking potato method is thanks to one of my readers. Nadia thank you for sharing!).

. While potatoes are cooking , boil 3 eggs and cooled them in ice water.

. Next, dice 3 eggs, 3-4 cucumbers, and 1/2 lb of ham. Also chop 3 Tbsp of dill and 1/2 cup of green onions. Place everything in a large pot.

.  In a separate large bowl, whisk together 8 cups of cold water, 1/3 cup of sour cream, 2 1/2 Tbsp of vinegar, 2 1/2 tsp of salt until combined. Pour the mixture in the pot with the rest of ingredients. Stir to combine and serve.

[Enjoy!]

----

Enjoy!

----
