= How to make Plov

== Ingredients
* 1 kg moderately fat lamb, shoulder or ribs
* 1 kg medium grain rice (paella type)
* 200-250 ml vegetable frying oil
* 1 kg carrot (preferably not young)
* 2-3 medium size onions
* 1-1.5 tbsp cumin
* 2-3 whole heads of garlic, the younger the better (optional)
* 1-2 long hot chillies (optional)
* salt to taste
* 5 liter heavy cast-iron cattle (dutch oven) or bigger, preferably round-bottomed

== Method
. Wash the rice under the tap until clear, cover with cold water and let it soaks for a while.
. Cut the meat with bones into match-box pieces.
. Cut the carrots into 0.5x0.5 cm thick sticks.
. Slice onions into thin rings or half-rings.
. Clean heads of garlic from the remains of roots and dirt.
. Heat oil in the cattle or dutch oven on a very high flame, deep-fry meat until golden-brown, in 3-4 batches. Fry the onions until golden, add meat to the cattle, stir well to prevent onion from burning. Add carrot, stir from time to time, until it starts to wilt and browns a little (15-20 min). Add 2/3 of the cumin - rub it in your palms a little to release flavor, stir gentliy to keep carrot from broking.
. Lower gas to moderate, pour hot water just to cover all the goods, add salt and let it simmer for 40 min to 1.5 hours until almost all water evaporate and meat became tender and juicy. Do not stir.
. Turn gas to max.
. Drain rice , place it on top the meat and vegs in one layer, stick the garlic and whole chillies in it, and carefully pour boiling water over it (place a spoon or ladle on top of the rice to keep the rice layer from washaway). Cover the rice with about 2 cm of water, let it boil. Add salt to make the water a bit over-salted. When water will go down the rice, reduce the gas a bit, keeping it boils rapidly. Check when it will evaporate and absorb into rice completely - rice should remain rather al dente. Make a holes in the rice to the bottom of a vessel to check the water level.
. Reduce gas to absolute min, cover tightly with the lid and let it steam 20 minutes. Turn of the heat, remove the garlic and chillies on the separate plate. Carefully mix rice with meat and carrots, if the rice tastes a bit blind add some salt, mix and let it stand for 5 minutes. Pile the plov on a big warmed plate and serve with garlic, chilies and plain thinly sliced tomato-sweet onions-chili-salt salad.
