= Spaghetti with meat tomato sauce

== Ingredients
Onions, tomato puree, minced meet, carrots, peppers, salt, paprika powder, cream, bayleef, rosemary, thyme, juniper pepper, spaghetti, lard, cheese(parmesan or pecorino romano)

== Step by step guide
. Get a pot and put a spoon of lard in it
. Turn on the spove for full power and let the lard melt
. Chop the onions and add them to the pot
. Stir the onions so they get browned evenly, reduce the heat under the pot by 2 degrees
. When the onions are lightly browned add the minced meat, add on top of the meat salt and paprika powder, and let it get lightly browned aswell
. After it´s done add in the tomato puree, chopped carrots, chopped peppers and whole juniper peppers
. Stir the sauce so it doesn´t burn on the bottom of the pot
. Let it all boil for at least 30 minutes
. Stir it again
. After this add the cream to the sauce and let it boil for next 10 minutes, also get another pot with water and salt for the spaghetti
. Turn on the stove under the pot of water for spaghetti
. Wait until the water is boiling and add the spaghetti and lower the heat on the stove by 3 degrees
. When the spaghetti are al dente, you can start serving

== Serving
Serve on a plate, first the spaghetti than the sauce and on top of the sauce grind the cheese. And enjoy your food
