= QUESADILLAS S TRHANÝM MASEM


== Na trhané maso:

• 750 g hovězího masa (zadního)
• 1 lžíce přepuštěného másla (řepkového oleje)
• 2 šalotky
• 1/2 lžičky sušeného zázvoru
• 1/4 lžičky kajenského pepře
• 150 ml vývaru nebo vody
• sůl
• pepř


== Na dokončení:

• tortilly
• kukuřice (v plechovce)
• čerstvý špenát
• cheddar
• krémový sýr (např. Lučina)
• rajčatové sugo (příp. kečup)


== Postup:

. Hovězí maso si osolíme, opepříme a okořeníme zázvorem a kajenským pepřem. Dno pomalého hrnce vytřeme přepuštěným máslem a maso na něj položíme.
. Přidáme nadrobno nasekanou šalotku a vývar. Pomalý hrnec zapneme na první stupeň a pečeme osm hodin. Zhruba po čtyřech hodinách je dobré maso otočit.
.  Hotové maso si vyndáme z hrnce a pomocí vidličky natrháme na tenké proužky. Natrhané maso zalijeme několika lžícemi zbylé omáčky, aby dostalo dobrou chuť.
. Teď už si rozložíme tortilly. Jednu tortillu potřeme rajčatovým sugem (případně kečupem) a druhou krémovým sýrem. Na tu tortillu s rajčatovým sugem rozložíme natrhané maso, posypeme kukuřicí, poklademe lístky čerstvého špenátu a posypeme nastrouhaným cheddarem. Nakonec ji překlopíme druhou tortillou s krémovým sýrem.
.  Rozpálíme si větší pánvičku a z obou stran tuto tortillu opečeme do zlatova.
.  Nakonec ji rozkrájíme na osm dílků (jako pizzu).

TIP: Hotové tortilly jsou skvělé s dipem ze zakysané smetany a nasekané pažitky nebo bazalky.
