= Vietnamese Rice Paper Rolls and Peanut Dipping Sauce

INGREDIENTS FOR ROLLS:


* sheets of round rice paper

* small cooked prawns/shrimp

* lettuce leaves

* dried vermicelli noodles

* mint leaves

* bean sprouts


INGREDIENTS FOR PEANUT DIPPING SAUCE:

* 1 tbsp peanut butter, preferably smooth (crunchy is ok too)

* 2 tbsp Hoisin Sauce

* 1 1/2 tbsp white vinegar (or lime juice)

* 1/3 cup milk (any fat %) (or water)

* 1 garlic clove, minced

* 1/2 tsp crushed chilli, samba oelak or other chilli paste, adjust to taste (optional)

INSTRUCTIONS FOR PEANUT SAUCE:

 1. Combine the Peanut Dipping Sauce ingredients.
 2. Mix briefly (it won’t come together), then microwave for 30 seconds. 
 3. Mix again until smooth. Set aside to cool. Adjust sour with vinegar, salt with salt and spiciness to taste. 
 4. Thickness can be adjusted with milk or water once cooled.


INSTRUCTIONS FOR ROLLS:

1. Peel the prawns, slice in half lengthwise and devein.

2. Remove the crunchy core of the lettuce leaves.

3. Tip – LETTUCE BUNDLE. Place some vermicelli noodles and bean sprouts in a lettuce leaf, then roll it up, finishing seam side down. Repeat.

4. Fill a large bowl with warm water. The bowl doesn’t need to be large enough to fit the whole rice paper in one go.

5. Place two rice papers together. Note which side is the smooth side – this is supposed to be the outside of the spring roll. Submerge the rice papers into the water (both of them at the same time, together) for 2 seconds.

6. Place both the rice papers (one on top of the other, they will stick together) on a board or the counter with the smooth side down.

7. On the top part of the rice paper, place 3 prawns with a mint leaf in between.

8. Place the lettuce bundle with the seam side down onto the middle of the rice paper.

9. Fold the left and right edges of the rice paper in, then starting from the bottom, roll up to cover the lettuce bundle. Then keep rolling firmly. The rice paper is sticky, it will seal itself.

10. Serve immediately with the peanut dipping sauce.
 
