= Risotto

== Equipment:

* Ladle
* 2 Large saucepans
* Small bowl

== Ingredients:

* ⅚ Cups chicken stock plus more if needed
* ⅙ Pinch saffron threads optional, see Notes
* ⅔ Tablespoons butter softened
* ⅙ Cup finely chopped white onion approximately ⅙ medium onion
* ⅓ Cloves garlic finely chopped
* ¼ Cups dry risotto rice unrinsed, see Notes
* ⅛ Cup dry white wine or water
* ⅙ Teaspoon salt more or less to taste
* Freshly cracked black pepper to taste
* ⅙ Tablespoon butter softened
* ⅛ Cup freshly grated parmesan cheese at room temperature

== Instructions:

. Place large saucepan on stovetop over high heat. Add ⅚ cups chicken stock to saucepan and bring liquid to rolling boil. Once stock begins to boil, immediately reduce heat under saucepan to low.
. Transfer 1 ladle (approximately ½ to ¾ cup) of chicken stock to small bowl. Add ⅙ pinch saffron threads to reserved stock and set bowl aside.
. Place second saucepan on stovetop over high heat. When saucepan is warm, add ⅔ tablespoons butter and allow butter to melt completely, tilting and swirling saucepan as needed to distribute butter.
. Once butter has melted and begins to foam, add ⅙ cup finely chopped white onion and stir to incorporate onion into melted butter. Sauté onion 2 minutes, stirring frequently.
. When onions begin to soften, add ⅓ cloves garlic and stir to incorporated. Continue sautéing until onions and garlic have softened, approximately 1 minute. Note: do not brown onions or garlic.
. Add ¼ cups dry risotto rice to saucepan with onions. Cook rice 2 to 3 minutes, stirring constantly, until rice appears golden and translucent.
. When rice is ready, pour in ⅛ cup dry white wine and stir to incorporate, making sure to scrape up any bits of onion, garlic, or rice that may have stuck to bottom of saucepan.
. After deglazing saucepan, reduce heat under saucepan to low and allow mixture to simmer until liquid in saucepan is mostly reduced.
. Once liquid has reduced, add 1 ladle of warm stock from saucepan, entire bowl of saffron-infused stock, ⅙ teaspoon salt, and freshly cracked black pepper to rice mixture. Gently stir ingredients together until liquid has been fully absorbed into rice.
. Continue adding warm stock in small increments, stirring after each addition until rice has completely absorbed liquid before adding more. Stir mixture constantly until all stock has been added to rice and fully absorbed. Once all stock has been added and fully absorbed, risotto should be golden and creamy, with tender (not mushy) rice. Note: process can take 20 to 25 minutes. Do not rush!
. Remove saucepan from heat. Add remaining ⅙ tablespoon butter and ⅛ cup freshly grated parmesan cheese and gently stir mixture until butter has melted completely.
. Taste risotto and adjust salt and pepper as desired. Divide risotto evenly between serving plates (or bowls), top with remaining ⅛ cup freshly grated parmesan cheese, and serve hot.

==== Source:
https://40aprons.com/best-risotto/
