
== Shit on a shingle
This recipe originates from the United Kingdom. Despite it's name, it is generaly considered as qoute "quite tasty".
It has not recieved any major updates since it's initial introduction, as it was made to be modular, easy to be
changed by every person who decides to, to their preferences..

=== Necessary ingredients:

* 4 1⁄2 oz. dried beef

* 2 cups of milk

* 2 tbs. butter

* 1⁄4 cup flour

* Salt and pepper

* 6 slices bread

=== Preparation instructions:

. Rinse dried beef under cold water to remove excess salt. Pat dry then rip up in smaller pieces
. Melt butter in pan
. Add dried beef. Cook 2-3 minutes until brown
. Add flour and mix with dried beef (it will look pretty dry)
. Add milk (reserve 1/4 cup for later), salt & pepper. Bring to boil
. Add remaining milk to thin to your desired likeness
. Serve over toast or waffles


==== Disclaimer
_Once the meal is prepared and served on a plate, it is to be consumed 'as is' and cannot be altered, resold, recycled or repurposed. 
If any of these terms are broken, your  warranty will be rendered void._
