= Tea time is a nice time
---
Since the dawn of time, tossing things into a boiling water was a popular craft among the humanity. 
We brew tincturae, concocti, and other hard Latin words. And why not? 
Meat becomes softer and loses some fat, poisonous herbs become medicine (in right dosage!)...
And the process is simply beautiful! The smell of lemongrass and ginger, the bitter of cloves, 
the rich amber tint of Ceylon's best leaves.
---

## Here are my top 2 recipes:
### Red Dragon in the Fog
In midst of cold rainy season there's no use in looking for the sun - it is wrapped tightly by the clouds and fog, preparing for the winter blizzards.
What woke me up in the morning of my college autumns was:

* good green tea with jasmine or mint - 2 tbsp per 250 ml of tea
* plant milk (pref. oat milk) - 20-40 ml per 250 ml
* grenadine syrup - to taste
* two vessels for preparation (ex. a teapot and a cup)
---
1. Brew your tea in a teapot. Note that water temperature should not exceed 85C or else leaves will loose their tste and gain bitterness.
2. Once tea brewed long enough, extract the tea leaves.
3. Add your milk.
4. Add some grenadine to the cup.
5. Pour you tea concoction to the cup, thoroughly stirring.
---

### Plague buster
---
Actually, it is not directly effective against plague. But it helps your plague-resistant immunity, so it works!

You should have:
* Rosehip with 5-angled tip (where the flower once was)
* Citrus
* Mint
* An apple, the red one
* Pepper
* Cinnamon or cloves
* Honey
 [If you have a --wet-- cough, add a little licorice to the list]

---
1. Slowly brew apple at 80 C for 5 mins.
2. Add your citrus of choise and brew some more.
3. Lower temperature to 50-60C (you will be able to touch the water without much pain, yet it will feel hot).
4. Add mint, pepper, cinnamon or cloves and leave it for 10-20 minutes.
5. Let it chill a little (to 30-40C).
6. Add honey and drink a lot!
---
