= Become a technical writer as a student

The goal of technical writers is to *help readers achive their goals*, by creating *straight forward and easy to follow documentation* for a product. 

== Prerequisites:
- educational foundation
- technical and tooling proficiency
- tendency to minimalism
- soft skills and communication

== Procedure:
. learn the core skills (writing skills, technical understanding, research skills)
. learn technical writing fundamentals
. develop technical knowledge
. learn documentation tools
. build a portfolio

== Writing skills:
- Technical writer should aim for straight forward documentation, without unnecessary fluff, but keeping the text accurate, clear, and effective (ACE)

*Forms of tech writing:*

  . Manuals, guides
  . Solutions or troubleshooting
  . Patch notes, release notes

*Formatting:*

Follow a specific style guide so your documentation is:

- reliable
- consistent
- scannable
- findable

*Style guides:*
. Apple style guide
. Google style guide
. Microsoft style guide


== Soft skills:

== Tools:



