= What is technical writing?


To become a technical writer 
we first need to define what is the purpose of technical writing.

== Its purpose
* Help readers achieve their goal whether it is to do or learn something.
* To be easily readable and accessible. Minimalism is key.
* To be accurate and clear about what actions to take to achieve the desired outcome.
 

== Ideal outcomes of correct implementation 

* Customer is able to understand the product's purpose and utilization without having to contact the developers.
* Sharing of information is swift and easy.
* Developers can troubleshoot code much faster.


= Essential skills

A technical writer combines communication with technical knowledge to create documentation.


include::Skills.adoc[]


= Employment as a Technical Writer

Technical writing is a rapidly growing field. Companies look for writers who can bridge the gap between complex engineering concepts and end-users.

include::Employment.adoc[]

= Technical writing style

include::technical writing style.adoc[]


= How to write correctly

include::How_to_write_correctly.adoc[]


