= Guide to Technical Writing


== What is technical writing?  
----
Your aim is to understand how product works, and help user to achieve their goal. 
Technical writing is used in manuals, guides, solutions, troubleshooting. 
 
Understand the subject → provide simple and imformative explanation to save work and stress for the readers.


----

== Technical docs style ≠ general writing style 

----
* Focus on readability, findability, accessibility, and ultimately the user 
 experience 
 * Some best practices: 
 * Use simple, translation-friendly language. 
 * Use visual structure and formatting to make the text easy to read. 
 * Focus on helping the reader accomplish a specific goal.
----


= Minimalism 
----
* User focus: action orientation 

* No fluff 

* Findability 

* Titles, headings 

* Error recovery, verification, troubleshooting 
----
== Simple language 
---- 
present (SVO) 

* Imperative 

* Infinitive 

* Active voice 
----
[.lead]
Where to practise: 

As a beginner you can explore and share your ideas and writings on these platforms: 

https://hashnode.com/[Hashnode] 

https://dev.to/[Dev.to]

= What is important for you as a future technical writer:  

* Doing your research, you have to know what you are writing about (read up on the subject matter). 

* As a TW you are not working alone! Talking to your colleagues is mandatory, because they give you feedback that is needed. 

* Create user personas – fictional characters that represent a user (Do not forget that you are going to be a content creator) 

== Technical writing skills: 

[cols="3,2"]
|===
|Writing and editing
|Strong writing and meticulous editing skills are crucial for producing clear, concise, and error-free documentation 
|Conveying information efectively
|They excel in breaking down complex information into understandable, user-friendly content
|Design
|They utilize design skills to create documents that are visually appealing and easy to navigate
|Use of technical tools
|Mastery over documentation tools and content management systems is essential for efficient document creation and management
|Research and audience analysis
|Technical writers constantly research and analyze their audience to tailor content that meets specific needs and preferences 
|Subject matter Expertise
|Technical writers must deeply understand the topics they cover to explain complex concepts clearly
|===

== Tools

[grid=cols]
|===
|WYSIWYG |Docs as code

|Text processor (MS Word, 
LibreOffice Writer, Google 
Docs…)
|Markup language (AsciiDoc, 
DocBook XML, Markdown…) + 
Text editor/IDE (Vim, VS Code, 
IntelliJ…)

| Granular control of all visual 
properties of all content 
elements
|Determines types of content 
elements -> Visual properties 
rendered through stylesheets

|Difficult to standardize, export, 
and version control
|Easier standardization, exporting, 
and version control

| Best for smaller doc sets with 
limited contributors
|Best for smaller doc sets with 
limited contributors
|Best for larger doc sets with 
more contributors
|===
